Repository javaparser/javaparser, pull requests merged in 2020-11, with the labels that each got.

#2906 fix jacoco and enable codecov.io action
  .github/workflows/maven_tests.yml
  javaparser-core-testing-bdd/pom.xml
  javaparser-core-testing/pom.xml
  javaparser-symbol-solver-testing/pom.xml
Labels: builds / releases

#2133 [TESTCASE] demonstrating resolution issue with variables de…
  javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/resolution/VariableResolutionTest.java
  javaparser-symbol-solver-testing/src/test/resources/VariableResolutionInVariousScopes.java.txt
Labels: PR - TESTCASE

#2901 Format and document the grammar (squash of #2901)
  javaparser-core/src/main/java/com/github/javaparser/TokenTypes.java
  javaparser-core/src/main/javacc-support/com/github/javaparser/GeneratedJavaParserBase.java
  javaparser-core/src/main/javacc/java.jj
Labels: Grammar

#2925 changelog entries for merged PRs
  changelog.md
Labels: builds / releases
