Repository javaparser/javaparser, pull requests merged in 2021-03, with the labels that each got.

#3148 Revert junit-pioneer version bump (#3121) and javassist classpool fix (#3134)
  javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/resolution/typesolvers/JarTypeSolver.java
  pom.xml
Labels: builds / releases, housekeeping

#3137 Fixed #3136 - ThisExpr isn't resolved correctly when it is in the scope of an ObjectCreationExpr
  javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/JavaParserFacade.java
  javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue3136Test.java
Labels: PR: Fixed

#3175 Verify builds test correctly under JDK16
  .github/workflows/maven_tests.yml
  javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/AbstractSymbolResolutionTest.java
Labels: Java 16 Support, PR: Development

#3178 Update changelog
  changelog.md
Labels: PR: Changed

#3179 Remove unused JUnit Pioneer dependency
  javaparser-symbol-solver-testing/pom.xml
  pom.xml
Labels: PR: Development

#3180 Publish to OSSRH rather than Bintray
  dev-files/settings.xml
  pom.xml
  run_release_perform.sh
  run_release_prepare.sh
Labels: PR: Development, builds / releases

#3049 Fixes #3048 (`JavaParserSymbolDeclaration#localVar` returning old declaration) and adds tests for `JavaParserSymbolDeclaration`
  javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/TryWithResourceContext.java
  javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserSymbolDeclaration.java
  javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarators/VariableSymbolDeclarator.java
  javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserSymbolDeclarationTest.java
Labels: PR: Changed

#3187 Fix issue #3173: Add isAnnotation() and asAnnotation() methods for ResolvedTypeDeclaration
  javaparser-core/src/main/java/com/github/javaparser/resolution/declarations/ResolvedAnnotationDeclaration.java
  javaparser-core/src/main/java/com/github/javaparser/resolution/declarations/ResolvedTypeDeclaration.java
  javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue3173Test.java
Labels: PR: Added

#3199 Fix surefire/jacoco configuration
  .github/workflows/maven_tests.yml
  codecov.yml
  javaparser-symbol-solver-testing/pom.xml
Labels: PR: Development

#3197 Implemented isAssignableBy for VoidType - now return `false` instead of throwing `UnsupportedOperationException`
  javaparser-core/src/main/java/com/github/javaparser/resolution/types/ResolvedVoidType.java
  javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/model/typesystem/VoidTypeTest.java
Labels: API or Behaviour Change, PR: Changed

#3210 Update readme template so that #3096 becomes permanent
  doc/readme.md
  readme.md
Labels: PR: Development
