Repository javaparser/javaparser, pull requests merged in 2021-09, with the labels that each got.

#3363 Reduce mvn verbosity on GitHub actions (and switch to mvnw)
  .github/workflows/maven_tests.yml
Labels: PR: Development

#3362 Fix "record" as non-type identifier in Java 16
  .github/workflows/maven_tests.yml
  changelog.md
  javaparser-core-testing/src/test/java/com/github/javaparser/ast/body/RecordDeclarationTest.java
  javaparser-core-testing/src/test/java/com/github/javaparser/ast/validator/Java14PreviewValidatorTest.java
  javaparser-core-testing/src/test/java/com/github/javaparser/ast/validator/Java15PreviewValidatorTest.java
  javaparser-core-testing/src/test/java/com/github/javaparser/ast/validator/Java16ValidatorTest.java
  javaparser-core-testing/src/test/java/com/github/javaparser/issues/Issue3255Test.java
  javaparser-core/src/main/java/com/github/javaparser/ast/validator/RecordAsTypeIdentifierNotAllowed.java
  javaparser-core/src/main/java/com/github/javaparser/ast/validator/language_level_validations/Java14Validator.java
  javaparser-core/src/main/java/com/github/javaparser/ast/validator/language_level_validations/Java16Validator.java
Labels: PR: Fixed

#3370 remove accidentally-added pom release backup files, and added it to gitignore to prevent them being re-added
  .gitignore
  javaparser-core-generators/pom.xml.releaseBackup
  javaparser-core-metamodel-generator/pom.xml.releaseBackup
  javaparser-core-serialization/pom.xml.releaseBackup
  javaparser-core-testing-bdd/pom.xml.releaseBackup
  javaparser-core-testing/pom.xml.releaseBackup
  javaparser-core/pom.xml.releaseBackup
  javaparser-symbol-solver-core/pom.xml.releaseBackup
  javaparser-symbol-solver-testing/pom.xml.releaseBackup
  pom.xml.releaseBackup
Labels: PR: Development

#3301 Java 11 is now the most used version
  javaparser-core-testing/src/test/java/com/github/javaparser/utils/ParserCollectionStrategyTest.java
  javaparser-core/src/main/java/com/github/javaparser/ParserConfiguration.java
  javaparser-core/src/main/java/com/github/javaparser/utils/CollectionStrategy.java
  javaparser-core/src/main/java/com/github/javaparser/utils/ParserCollectionStrategy.java
Labels: API or Behaviour Change, PR: Changed
