Repository javaparser/javaparser, pull requests merged in 2021-12, with the labels that each got.

#3428 Issue #3419 - Fixed bug in `Difference.java`
  javaparser-core-testing/src/test/java/com/github/javaparser/printer/lexicalpreservation/LexicalPreservingPrinterTest.java
  javaparser-core/src/main/java/com/github/javaparser/printer/lexicalpreservation/Difference.java
Labels: PR: Fixed

#3432 Add a missing hashCode() method
  javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistTypeParameter.java
Labels: PR: Fixed

#3438 Add erasure on parametrized type
  javaparser-core/src/main/java/com/github/javaparser/resolution/declarations/ResolvedTypeParameterDeclaration.java
  javaparser-core/src/main/java/com/github/javaparser/resolution/types/ResolvedArrayType.java
  javaparser-core/src/main/java/com/github/javaparser/resolution/types/ResolvedReferenceType.java
  javaparser-core/src/main/java/com/github/javaparser/resolution/types/ResolvedType.java
  javaparser-core/src/main/java/com/github/javaparser/resolution/types/ResolvedTypeVariable.java
  javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserAnonymousClassDeclaration.java
  javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/declarations/JavaParserTypeParameter.java
  javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javassistmodel/JavassistTypeParameter.java
  javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/reflectionmodel/ReflectionTypeParameter.java
  javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/model/typesystem/ReferenceTypeTest.java
Labels: PR: Added

#3034 Fixed Resolution of generic types
  javaparser-core/src/main/java/com/github/javaparser/ast/type/ClassOrInterfaceType.java
  javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/ClassOrInterfaceDeclarationContext.java
  javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/ast/type/ClassOrInterfaceTypeTest.java
  javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue1814Test.java
  javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue2397Test.java
  javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue2481Test.java
  javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue3112Test.java
  javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/resolution/TypeResolutionWithSameNameTest.java
Labels: API or Behaviour Change
