Repository javaparser/javaparser, pull requests merged in 2021-05, with the labels that each got.

#3254 Include and use a Maven wrapper
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  fixup.sh
  mvnw
  mvnw.cmd
  run_core_generators.sh
  run_core_metamodel_generator.sh
  run_release_perform.sh
  run_release_prepare.sh
Labels: PR: Development

#3231 Handle possibility of tokens not being available
  javaparser-core-testing/src/test/java/com/github/javaparser/ast/expr/ThisExprTest.java
  javaparser-core/src/main/javacc-support/com/github/javaparser/GeneratedJavaParserBase.java
Labels: PR: Fixed

#3247 Recover wrong statements no only to ';', but to '}' (not including) as well
  javaparser-core-testing/src/test/java/com/github/javaparser/ParseErrorRecoveryTest.java
  javaparser-core-testing/src/test/resources/com/github/javaparser/Sample.java
  javaparser-core/src/main/javacc-support/com/github/javaparser/GeneratedJavaParserBase.java
  javaparser-core/src/main/javacc/java.jj
Labels: PR: Added, error recovery

#3256 fixes #3255 -- bugfix grammar case when using `record` to as an identifier
  javaparser-core-testing/src/test/java/com/github/javaparser/issues/Issue3255Test.java
  javaparser-core/src/main/javacc/java.jj
Labels: PR: Fixed

#3263 update features.md -- fixed release version and date of records support, status of java 16 sealed classes to 2nd preview, and java 17 features
  FEATURES.md
Labels: PR: Fixed
